name: byte_bloc
description: ByteBloc simplify binary array parsing for C/C++ structures.
version: 0.1.6
repository: https://github.com/AlexVegner/byte_bloc
issue_tracker: https://github.com/AlexVegner/byte_bloc/issues
homepage: https://github.com/AlexVegner/byte_bloc

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  convert: ^2.1.1

dev_dependencies:
  test: ^1.9.4
